// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Telerik.Outlook.Infrastructure.UIMaps.CalendarUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class CalendarUIMap
    {
        
        /// <summary>
        /// ClickDay
        /// </summary>
        public void ClickDay()
        {
            #region Variable Declarations
            WpfCustom uICalendarScheduleViewCustom = this.UIMarktelerikdomaincomWindow.UIItemCustom.UICalendarScheduleViewCustom;
            #endregion

            // Click 'calendarScheduleView' custom control
            Mouse.Click(uICalendarScheduleViewCustom, new Point(822, 482));
        }
        
        #region Properties
        public UIMarktelerikdomaincomWindow UIMarktelerikdomaincomWindow
        {
            get
            {
                if ((this.mUIMarktelerikdomaincomWindow == null))
                {
                    this.mUIMarktelerikdomaincomWindow = new UIMarktelerikdomaincomWindow();
                }
                return this.mUIMarktelerikdomaincomWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMarktelerikdomaincomWindow mUIMarktelerikdomaincomWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMarktelerikdomaincomWindow : WpfWindow
    {
        
        public UIMarktelerikdomaincomWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "mark@telerikdomain.com - calendar";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("mark@telerikdomain.com - calendar");
            #endregion
        }
        
        #region Properties
        public UIItemCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom(this);
                }
                return this.mUIItemCustom;
            }
        }
        
        public WpfButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "OKButton";
                    this.mUIOKButton.WindowTitles.Add("mark@telerikdomain.com - calendar");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private UIItemCustom mUIItemCustom;
        
        private WpfButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCustom : WpfCustom
    {
        
        public UIItemCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.MainView";
            this.WindowTitles.Add("mark@telerikdomain.com - calendar");
            #endregion
        }
        
        #region Properties
        public UICalendarScheduleViewCustom UICalendarScheduleViewCustom
        {
            get
            {
                if ((this.mUICalendarScheduleViewCustom == null))
                {
                    this.mUICalendarScheduleViewCustom = new UICalendarScheduleViewCustom(this);
                }
                return this.mUICalendarScheduleViewCustom;
            }
        }
        #endregion
        
        #region Fields
        private UICalendarScheduleViewCustom mUICalendarScheduleViewCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICalendarScheduleViewCustom : WpfCustom
    {
        
        public UICalendarScheduleViewCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.RadScheduleView";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "calendarScheduleView";
            this.WindowTitles.Add("mark@telerikdomain.com - calendar");
            #endregion
        }
        
        #region Properties
        public WpfListItem UIFfe135114b79414faa04ListItem
        {
            get
            {
                if ((this.mUIFfe135114b79414faa04ListItem == null))
                {
                    this.mUIFfe135114b79414faa04ListItem = new WpfListItem(this);
                    #region Search Criteria
                    this.mUIFfe135114b79414faa04ListItem.SearchProperties[WpfListItem.PropertyNames.Name] = "ffe13511-4b79-414f-aa04-4d953d5547e7 : 19-Aug-15 12:00:00 AM - 20-Aug-15 12:00:00" +
                        " AM";
                    this.mUIFfe135114b79414faa04ListItem.WindowTitles.Add("mark@telerikdomain.com - calendar");
                    #endregion
                }
                return this.mUIFfe135114b79414faa04ListItem;
            }
        }
        #endregion
        
        #region Fields
        private WpfListItem mUIFfe135114b79414faa04ListItem;
        #endregion
    }
}
