// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Telerik.Outlook.Infrastructure.UIMaps.ComposeNewMailUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class ComposeNewMailUIMap
    {
        
        /// <summary>
        /// ClickedEmailSubjectTextBox
        /// </summary>
        public void ClickedEmailSubjectTextBox()
        {
            #region Variable Declarations
            WpfEdit uISubjectTextBox = this.UINewMessageHTMLWindow.UISubjectTextBox;
            #endregion

            // Click text box numbered 3 in 'Untitled - Message (HTML)' window
            Mouse.Click(uISubjectTextBox, new Point(54, 7));
        }
        
        /// <summary>
        /// ClickedInNewEmailTextArea
        /// </summary>
        public void ClickedInNewEmailTextArea()
        {
            #region Variable Declarations
            WpfControl uIMessageRadRichTextBoxDocument = this.UINewMessageHTMLWindow.UIMessageRadRichTextBoxDocument;
            #endregion

            // Click 'radRichTextBox' document
            Mouse.Click(uIMessageRadRichTextBoxDocument, new Point(409, 104));
        }
        
        /// <summary>
        /// ClickedRecipientAddressTextBox
        /// </summary>
        public void ClickedRecipientAddressTextBox()
        {
            #region Variable Declarations
            WpfEdit uIRecipientTextBox = this.UINewMessageHTMLWindow.UIRecipientTextBox;
            #endregion

            // Click text box
            Mouse.Click(uIRecipientTextBox, new Point(24, 11));
        }
        
        /// <summary>
        /// ClickedSendMailButton
        /// </summary>
        public void ClickedSendMailButton()
        {
            #region Variable Declarations
            WpfButton uISendButton = this.UINewMessageHTMLWindow.UISendButton;
            #endregion

            // Click 'RadButton' button
            Mouse.Click(uISendButton, new Point(14, 23));
        }
        
        /// <summary>
        /// EnterMailSubject - Use 'EnterSubjectInSubjectTextBoxParams' to pass parameters into this method.
        /// </summary>
        public void EnterSubjectInSubjectTextBox()
        {
            #region Variable Declarations
            WpfEdit uISubjectTextBox = this.UINewMessageHTMLWindow.UISubjectTextBox;
            #endregion

            // Type 'hey there friend' in text box numbered 3 in 'Untitled - Message (HTML)' window
            uISubjectTextBox.Text = this.EnterSubjectInSubjectTextBoxParams.UISubjectTextBoxText;
        }
        
        /// <summary>
        /// TypedEmailTextInNewEmailTextArea - Use 'TypedEmailTextInNewEmailTextAreaParams' to pass parameters into this method.
        /// </summary>
        public void TypedEmailTextInNewEmailTextArea()
        {
            #region Variable Declarations
            WpfWindow uINewMessageHTMLWindow = this.UINewMessageHTMLWindow;
            #endregion

            // Type 'shalom{Space}friend{Space}you{Space}are{Space}missing' in 'Untitled - Message (HTML)' window
            Keyboard.SendKeys(uINewMessageHTMLWindow, this.TypedEmailTextInNewEmailTextAreaParams.UINewMessageHTMLWindowSendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// TypedValidEmailAddressInRecipientTextBox - Use 'TypedValidEmailAddressInRecipientTextBoxParams' to pass parameters into this method.
        /// </summary>
        public void TypedValidEmailAddressInRecipientTextBox()
        {
            #region Variable Declarations
            WpfEdit uIRecipientTextBox = this.UINewMessageHTMLWindow.UIRecipientTextBox;
            #endregion

            // Type 'mark@telerikdomain.com' in text box
            uIRecipientTextBox.Text = this.TypedValidEmailAddressInRecipientTextBoxParams.UIRecipientTextBoxText;
        }
        
        #region Properties
        public virtual EnterSubjectInSubjectTextBoxParams EnterSubjectInSubjectTextBoxParams
        {
            get
            {
                if ((this.mEnterSubjectInSubjectTextBoxParams == null))
                {
                    this.mEnterSubjectInSubjectTextBoxParams = new EnterSubjectInSubjectTextBoxParams();
                }
                return this.mEnterSubjectInSubjectTextBoxParams;
            }
        }
        
        public virtual TypedEmailTextInNewEmailTextAreaParams TypedEmailTextInNewEmailTextAreaParams
        {
            get
            {
                if ((this.mTypedEmailTextInNewEmailTextAreaParams == null))
                {
                    this.mTypedEmailTextInNewEmailTextAreaParams = new TypedEmailTextInNewEmailTextAreaParams();
                }
                return this.mTypedEmailTextInNewEmailTextAreaParams;
            }
        }
        
        public virtual TypedValidEmailAddressInRecipientTextBoxParams TypedValidEmailAddressInRecipientTextBoxParams
        {
            get
            {
                if ((this.mTypedValidEmailAddressInRecipientTextBoxParams == null))
                {
                    this.mTypedValidEmailAddressInRecipientTextBoxParams = new TypedValidEmailAddressInRecipientTextBoxParams();
                }
                return this.mTypedValidEmailAddressInRecipientTextBoxParams;
            }
        }
        
        public UINewMessageHTMLWindow UINewMessageHTMLWindow
        {
            get
            {
                if ((this.mUINewMessageHTMLWindow == null))
                {
                    this.mUINewMessageHTMLWindow = new UINewMessageHTMLWindow();
                }
                return this.mUINewMessageHTMLWindow;
            }
        }
        #endregion
        
        #region Fields
        private EnterSubjectInSubjectTextBoxParams mEnterSubjectInSubjectTextBoxParams;
        
        private TypedEmailTextInNewEmailTextAreaParams mTypedEmailTextInNewEmailTextAreaParams;
        
        private TypedValidEmailAddressInRecipientTextBoxParams mTypedValidEmailAddressInRecipientTextBoxParams;
        
        private UINewMessageHTMLWindow mUINewMessageHTMLWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'EnterMailSubject'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class EnterSubjectInSubjectTextBoxParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'hey there friend' in text box numbered 3 in 'Untitled - Message (HTML)' window
        /// </summary>
        public string UISubjectTextBoxText = "hey there friend";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TypedEmailTextInNewEmailTextArea'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class TypedEmailTextInNewEmailTextAreaParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'shalom{Space}friend{Space}you{Space}are{Space}missing' in 'Untitled - Message (HTML)' window
        /// </summary>
        public string UINewMessageHTMLWindowSendKeys = "shalom{Space}friend{Space}you{Space}are{Space}missing";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TypedValidEmailAddressInRecipientTextBox'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class TypedValidEmailAddressInRecipientTextBoxParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'mark@telerikdomain.com' in text box
        /// </summary>
        public string UIRecipientTextBoxText = "mark@telerikdomain.com";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UINewMessageHTMLWindow : WpfWindow
    {
        
        public UINewMessageHTMLWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Untitled - Message (HTML)";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Untitled - Message (HTML)");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIRecipientTextBox
        {
            get
            {
                if ((this.mUIRecipientTextBox == null))
                {
                    this.mUIRecipientTextBox = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIRecipientTextBox.WindowTitles.Add("Untitled - Message (HTML)");
                    #endregion
                }
                return this.mUIRecipientTextBox;
            }
        }
        
        public WpfEdit UISubjectTextBox
        {
            get
            {
                if ((this.mUISubjectTextBox == null))
                {
                    this.mUISubjectTextBox = new WpfEdit(this);
                    #region Search Criteria
                    this.mUISubjectTextBox.SearchProperties[WpfEdit.PropertyNames.Instance] = "3";
                    this.mUISubjectTextBox.WindowTitles.Add("Untitled - Message (HTML)");
                    #endregion
                }
                return this.mUISubjectTextBox;
            }
        }
        
        public WpfControl UIMessageRadRichTextBoxDocument
        {
            get
            {
                if ((this.mUIMessageRadRichTextBoxDocument == null))
                {
                    this.mUIMessageRadRichTextBoxDocument = new WpfControl(this);
                    #region Search Criteria
                    this.mUIMessageRadRichTextBoxDocument.SearchProperties[WpfControl.PropertyNames.ControlType] = "Document";
                    this.mUIMessageRadRichTextBoxDocument.SearchProperties[WpfControl.PropertyNames.AutomationId] = "radRichTextBox";
                    this.mUIMessageRadRichTextBoxDocument.WindowTitles.Add("Untitled - Message (HTML)");
                    #endregion
                }
                return this.mUIMessageRadRichTextBoxDocument;
            }
        }
        
        public WpfButton UISendButton
        {
            get
            {
                if ((this.mUISendButton == null))
                {
                    this.mUISendButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISendButton.SearchProperties[WpfButton.PropertyNames.HelpText] = "RadButton";
                    this.mUISendButton.SearchProperties[WpfButton.PropertyNames.Instance] = "3";
                    this.mUISendButton.WindowTitles.Add("Untitled - Message (HTML)");
                    #endregion
                }
                return this.mUISendButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIRecipientTextBox;
        
        private WpfEdit mUISubjectTextBox;
        
        private WpfControl mUIMessageRadRichTextBoxDocument;
        
        private WpfButton mUISendButton;
        #endregion
    }
}
