// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Telerik.Outlook.Infrastructure.UIMaps.MailDisplayUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class MailDisplayUIMap
    {
        
        #region Properties
        public UIMarktelerikdomaincomWindow UIMarktelerikdomaincomWindow
        {
            get
            {
                if ((this.mUIMarktelerikdomaincomWindow == null))
                {
                    this.mUIMarktelerikdomaincomWindow = new UIMarktelerikdomaincomWindow();
                }
                return this.mUIMarktelerikdomaincomWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMarktelerikdomaincomWindow mUIMarktelerikdomaincomWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIMarktelerikdomaincomWindow : WpfWindow
    {
        
        public UIMarktelerikdomaincomWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "mark@telerikdomain.com - My Application";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("mark@telerikdomain.com - My Application");
            #endregion
        }
        
        #region Properties
        public UIItemCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom(this);
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIItemCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemCustom : WpfCustom
    {
        
        public UIItemCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.MainView";
            this.WindowTitles.Add("mark@telerikdomain.com - My Application");
            #endregion
        }
        
        #region Properties
        public WpfButton UIRadRibbonButtonReply
        {
            get
            {
                if ((this.mUIRadRibbonButtonReply == null))
                {
                    this.mUIRadRibbonButtonReply = new WpfButton(this);
                    #region Search Criteria
                    this.mUIRadRibbonButtonReply.SearchProperties[WpfButton.PropertyNames.HelpText] = "RadRibbonButton";
                    this.mUIRadRibbonButtonReply.WindowTitles.Add("mark@telerikdomain.com - My Application");
                    #endregion
                }
                return this.mUIRadRibbonButtonReply;
            }
        }
        
        public WpfButton UIRadRibbonButtonPopOut
        {
            get
            {
                if ((this.mUIRadRibbonButtonPopOut == null))
                {
                    this.mUIRadRibbonButtonPopOut = new WpfButton(this);
                    #region Search Criteria
                    this.mUIRadRibbonButtonPopOut.SearchProperties[WpfButton.PropertyNames.HelpText] = "RadRibbonButton";
                    this.mUIRadRibbonButtonPopOut.SearchProperties[WpfButton.PropertyNames.Instance] = "4";
                    this.mUIRadRibbonButtonPopOut.WindowTitles.Add("mark@telerikdomain.com - My Application");
                    #endregion
                }
                return this.mUIRadRibbonButtonPopOut;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIRadRibbonButtonReply;
        
        private WpfButton mUIRadRibbonButtonPopOut;
        #endregion
    }
}
