// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Telerik.Outlook.Infrastructure.UIMaps.MailsTableUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class MailsTableUIMap
    {
        
        #region Properties
        public UIMarktelerikdomaincomWindow UIMarktelerikdomaincomWindow
        {
            get
            {
                if ((this.mUIMarktelerikdomaincomWindow == null))
                {
                    this.mUIMarktelerikdomaincomWindow = new UIMarktelerikdomaincomWindow();
                }
                return this.mUIMarktelerikdomaincomWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMarktelerikdomaincomWindow mUIMarktelerikdomaincomWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIMarktelerikdomaincomWindow : WpfWindow
    {
        
        public UIMarktelerikdomaincomWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "mark@telerikdomain.com - My Application";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("mark@telerikdomain.com - My Application");
            #endregion
        }
        
        #region Properties
        public UIItemCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom(this);
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIItemCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemCustom : WpfCustom
    {
        
        public UIItemCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.MainView";
            this.WindowTitles.Add("mark@telerikdomain.com - My Application");
            #endregion
        }
        
        #region Properties
        public UILoadingProgressBar UILoadingProgressBar
        {
            get
            {
                if ((this.mUILoadingProgressBar == null))
                {
                    this.mUILoadingProgressBar = new UILoadingProgressBar(this);
                }
                return this.mUILoadingProgressBar;
            }
        }
        
        public UISearchWatermarkTextBEdit UISearchWatermarkTextBEdit
        {
            get
            {
                if ((this.mUISearchWatermarkTextBEdit == null))
                {
                    this.mUISearchWatermarkTextBEdit = new UISearchWatermarkTextBEdit(this);
                }
                return this.mUISearchWatermarkTextBEdit;
            }
        }
        
        public UIGridViewTable UIGridViewTable
        {
            get
            {
                if ((this.mUIGridViewTable == null))
                {
                    this.mUIGridViewTable = new UIGridViewTable(this);
                }
                return this.mUIGridViewTable;
            }
        }
        #endregion
        
        #region Fields
        private UILoadingProgressBar mUILoadingProgressBar;
        
        private UISearchWatermarkTextBEdit mUISearchWatermarkTextBEdit;
        
        private UIGridViewTable mUIGridViewTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UILoadingProgressBar : WpfProgressBar
    {
        
        public UILoadingProgressBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfProgressBar.PropertyNames.AutomationId] = "BusyIndicator";
            this.WindowTitles.Add("mark@telerikdomain.com - My Application");
            #endregion
        }
        
        #region Properties
        public WpfTable UIGridViewTable
        {
            get
            {
                if ((this.mUIGridViewTable == null))
                {
                    this.mUIGridViewTable = new WpfTable(this);
                    #region Search Criteria
                    this.mUIGridViewTable.SearchProperties[WpfTable.PropertyNames.AutomationId] = "gridView";
                    this.mUIGridViewTable.WindowTitles.Add("mark@telerikdomain.com - My Application");
                    #endregion
                }
                return this.mUIGridViewTable;
            }
        }
        #endregion
        
        #region Fields
        private WpfTable mUIGridViewTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UISearchWatermarkTextBEdit : WpfEdit
    {
        
        public UISearchWatermarkTextBEdit(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "SearchWatermarkTextBox";
            this.WindowTitles.Add("mark@telerikdomain.com - My Application");
            #endregion
        }
        
        #region Properties
        public WpfText UISearchCurrentMailboxText
        {
            get
            {
                if ((this.mUISearchCurrentMailboxText == null))
                {
                    this.mUISearchCurrentMailboxText = new WpfText(this);
                    #region Search Criteria
                    this.mUISearchCurrentMailboxText.SearchProperties[WpfText.PropertyNames.Name] = "Search Current Mailbox";
                    this.mUISearchCurrentMailboxText.WindowTitles.Add("mark@telerikdomain.com - My Application");
                    #endregion
                }
                return this.mUISearchCurrentMailboxText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUISearchCurrentMailboxText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIGridViewTable : WpfTable
    {
        
        public UIGridViewTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTable.PropertyNames.AutomationId] = "gridView";
            this.WindowTitles.Add("mark@telerikdomain.com - My Application");
            #endregion
        }
        
        #region Properties
        public UIRow_0Row UIRow_0Row
        {
            get
            {
                if ((this.mUIRow_0Row == null))
                {
                    this.mUIRow_0Row = new UIRow_0Row(this);
                }
                return this.mUIRow_0Row;
            }
        }
        
        public UIRow_2Row UIRow_2Row
        {
            get
            {
                if ((this.mUIRow_2Row == null))
                {
                    this.mUIRow_2Row = new UIRow_2Row(this);
                }
                return this.mUIRow_2Row;
            }
        }
        
        public UIRow_3Row UIRow_3Row
        {
            get
            {
                if ((this.mUIRow_3Row == null))
                {
                    this.mUIRow_3Row = new UIRow_3Row(this);
                }
                return this.mUIRow_3Row;
            }
        }
        #endregion
        
        #region Fields
        private UIRow_0Row mUIRow_0Row;
        
        private UIRow_2Row mUIRow_2Row;
        
        private UIRow_3Row mUIRow_3Row;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIRow_0Row : WpfRow
    {
        
        public UIRow_0Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfRow.PropertyNames.AutomationId] = "Row_0";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("mark@telerikdomain.com - My Application");
            #endregion
        }
        
        #region Properties
        public UIF2c15a3b990041f3b184Cell UIF2c15a3b990041f3b184Cell
        {
            get
            {
                if ((this.mUIF2c15a3b990041f3b184Cell == null))
                {
                    this.mUIF2c15a3b990041f3b184Cell = new UIF2c15a3b990041f3b184Cell(this);
                }
                return this.mUIF2c15a3b990041f3b184Cell;
            }
        }
        
        public UIItem0Cell UIItem0Cell
        {
            get
            {
                if ((this.mUIItem0Cell == null))
                {
                    this.mUIItem0Cell = new UIItem0Cell(this);
                }
                return this.mUIItem0Cell;
            }
        }
        #endregion
        
        #region Fields
        private UIF2c15a3b990041f3b184Cell mUIF2c15a3b990041f3b184Cell;
        
        private UIItem0Cell mUIItem0Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIF2c15a3b990041f3b184Cell : WpfCell
    {
        
        public UIF2c15a3b990041f3b184Cell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "SUBJECT";
            this.SearchProperties[WpfCell.PropertyNames.AutomationId] = "Cell_0_1";
            this.WindowTitles.Add("mark@telerikdomain.com - My Application");
            #endregion
        }
        
        #region Properties
        public WpfText UIF2c15a3b990041f3b184Text
        {
            get
            {
                if ((this.mUIF2c15a3b990041f3b184Text == null))
                {
                    this.mUIF2c15a3b990041f3b184Text = new WpfText(this);
                    #region Search Criteria
                    this.mUIF2c15a3b990041f3b184Text.SearchProperties[WpfText.PropertyNames.AutomationId] = "CellElement_0_1";
                    this.mUIF2c15a3b990041f3b184Text.WindowTitles.Add("mark@telerikdomain.com - My Application");
                    #endregion
                }
                return this.mUIF2c15a3b990041f3b184Text;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIF2c15a3b990041f3b184Text;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItem0Cell : WpfCell
    {
        
        public UIItem0Cell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "HeaderCell_3";
            this.SearchProperties[WpfCell.PropertyNames.AutomationId] = "Cell_0_3";
            this.WindowTitles.Add("mark@telerikdomain.com - My Application");
            #endregion
        }
        
        #region Properties
        public WpfCustom UICellElement_0_3Custom
        {
            get
            {
                if ((this.mUICellElement_0_3Custom == null))
                {
                    this.mUICellElement_0_3Custom = new WpfCustom(this);
                    #region Search Criteria
                    this.mUICellElement_0_3Custom.SearchProperties[WpfControl.PropertyNames.ClassName] = null;
                    this.mUICellElement_0_3Custom.SearchProperties[WpfControl.PropertyNames.AutomationId] = "CellElement_0_3";
                    this.mUICellElement_0_3Custom.WindowTitles.Add("mark@telerikdomain.com - My Application");
                    #endregion
                }
                return this.mUICellElement_0_3Custom;
            }
        }
        #endregion
        
        #region Fields
        private WpfCustom mUICellElement_0_3Custom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIRow_2Row : WpfRow
    {
        
        public UIRow_2Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfRow.PropertyNames.AutomationId] = "Row_2";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("mark@telerikdomain.com - My Application");
            #endregion
        }
        
        #region Properties
        public UIItem1Cell UIItem1Cell
        {
            get
            {
                if ((this.mUIItem1Cell == null))
                {
                    this.mUIItem1Cell = new UIItem1Cell(this);
                }
                return this.mUIItem1Cell;
            }
        }
        #endregion
        
        #region Fields
        private UIItem1Cell mUIItem1Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItem1Cell : WpfCell
    {
        
        public UIItem1Cell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "HeaderCell_3";
            this.SearchProperties[WpfCell.PropertyNames.AutomationId] = "Cell_2_3";
            this.WindowTitles.Add("mark@telerikdomain.com - My Application");
            #endregion
        }
        
        #region Properties
        public WpfCustom UICellElement_2_3Custom
        {
            get
            {
                if ((this.mUICellElement_2_3Custom == null))
                {
                    this.mUICellElement_2_3Custom = new WpfCustom(this);
                    #region Search Criteria
                    this.mUICellElement_2_3Custom.SearchProperties[WpfControl.PropertyNames.ClassName] = null;
                    this.mUICellElement_2_3Custom.SearchProperties[WpfControl.PropertyNames.AutomationId] = "CellElement_2_3";
                    this.mUICellElement_2_3Custom.WindowTitles.Add("mark@telerikdomain.com - My Application");
                    #endregion
                }
                return this.mUICellElement_2_3Custom;
            }
        }
        #endregion
        
        #region Fields
        private WpfCustom mUICellElement_2_3Custom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIRow_3Row : WpfRow
    {
        
        public UIRow_3Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfRow.PropertyNames.AutomationId] = "Row_3";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("mark@telerikdomain.com - My Application");
            #endregion
        }
        
        #region Properties
        public UIItemOutlookInspiredACell UIItemOutlookInspiredACell
        {
            get
            {
                if ((this.mUIItemOutlookInspiredACell == null))
                {
                    this.mUIItemOutlookInspiredACell = new UIItemOutlookInspiredACell(this);
                }
                return this.mUIItemOutlookInspiredACell;
            }
        }
        #endregion
        
        #region Fields
        private UIItemOutlookInspiredACell mUIItemOutlookInspiredACell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemOutlookInspiredACell : WpfCell
    {
        
        public UIItemOutlookInspiredACell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "HeaderCell_3";
            this.SearchProperties[WpfCell.PropertyNames.AutomationId] = "Cell_3_3";
            this.WindowTitles.Add("mark@telerikdomain.com - My Application");
            #endregion
        }
        
        #region Properties
        public WpfText UICellElement_3_3Text
        {
            get
            {
                if ((this.mUICellElement_3_3Text == null))
                {
                    this.mUICellElement_3_3Text = new WpfText(this);
                    #region Search Criteria
                    this.mUICellElement_3_3Text.SearchProperties[WpfText.PropertyNames.AutomationId] = "CellElement_3_3";
                    this.mUICellElement_3_3Text.WindowTitles.Add("mark@telerikdomain.com - My Application");
                    #endregion
                }
                return this.mUICellElement_3_3Text;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUICellElement_3_3Text;
        #endregion
    }
}
