// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Telerik.Outlook.Infrastructure.UIMaps.NavBarUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class NavBarUIMap
    {
        
        /// <summary>
        /// ClickCalendarTab
        /// </summary>
        public void ClickCalendarTab()
        {
            #region Variable Declarations
            WpfCustom uIRadOutlookBarItemCustomCalendar = this.UIMarktelerikdomaincomWindowMail.UIItemCustom.UIOutlookBarCustom.UIRadOutlookBarItemCustomCalendar;
            #endregion

            // Click 'RadOutlookBarItem' custom control
            Mouse.Click(uIRadOutlookBarItemCustomCalendar, new Point(98, 17));
        }
        
        /// <summary>
        /// ClickDeletedItemsFolder
        /// </summary>
        public void ClickDeletedItemsFolder()
        {
            #region Variable Declarations
            WpfCustom uIOutlookBarCustom = this.UIMarktelerikdomaincomWindowMail.UIItemCustom.UIOutlookBarCustom;
            #endregion

            // Click 'OutlookBar' custom control
            Mouse.Click(uIOutlookBarCustom, new Point(95, 111));
        }
        
        /// <summary>
        /// ClickInboxFolder
        /// </summary>
        public void ClickInboxFolder()
        {
            #region Variable Declarations
            WpfCustom uIOutlookBarCustom = this.UIMarktelerikdomaincomWindowMail.UIItemCustom.UIOutlookBarCustom;
            #endregion

            // Click 'OutlookBar' custom control
            Mouse.Click(uIOutlookBarCustom, new Point(72, 66));
        }
        
        /// <summary>
        /// ClickMailTab
        /// </summary>
        public void ClickMailTab()
        {
            #region Variable Declarations
            WpfCustom uIRadOutlookBarItemCustomMail = this.UIMarktelerikdomaincomWindowMail.UIItemCustom.UIOutlookBarCustom.UIRadOutlookBarItemCustomMail;
            #endregion

            // Click 'RadOutlookBarItem' custom control
            Mouse.Click(uIRadOutlookBarItemCustomMail, new Point(95, 19));
        }
        
        /// <summary>
        /// ClickSentItemsFolder
        /// </summary>
        public void ClickSentItemsFolder()
        {
            #region Variable Declarations
            WpfCustom uIOutlookBarCustom = this.UIMarktelerikdomaincomWindowMail.UIItemCustom.UIOutlookBarCustom;
            #endregion

            // Click 'OutlookBar' custom control
            Mouse.Click(uIOutlookBarCustom, new Point(82, 82));
        }
        
        #region Properties
        public UIMarktelerikdomaincomWindowMail UIMarktelerikdomaincomWindowMail
        {
            get
            {
                if ((this.mUIMarktelerikdomaincomWindowMail == null))
                {
                    this.mUIMarktelerikdomaincomWindowMail = new UIMarktelerikdomaincomWindowMail();
                }
                return this.mUIMarktelerikdomaincomWindowMail;
            }
        }
        
        public UIMarktelerikdomaincomWindowCalendar UIMarktelerikdomaincomWindowCalendar
        {
            get
            {
                if ((this.mUIMarktelerikdomaincomWindowCalendar == null))
                {
                    this.mUIMarktelerikdomaincomWindowCalendar = new UIMarktelerikdomaincomWindowCalendar();
                }
                return this.mUIMarktelerikdomaincomWindowCalendar;
            }
        }
        #endregion
        
        #region Fields
        private UIMarktelerikdomaincomWindowMail mUIMarktelerikdomaincomWindowMail;
        
        private UIMarktelerikdomaincomWindowCalendar mUIMarktelerikdomaincomWindowCalendar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIMarktelerikdomaincomWindowMail : WpfWindow
    {
        
        public UIMarktelerikdomaincomWindowMail()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "mark@telerikdomain.com - My Application";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("mark@telerikdomain.com - My Application");
            #endregion
        }
        
        #region Properties
        public UIItemCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom(this);
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIItemCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemCustom : WpfCustom
    {
        
        public UIItemCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.MainView";
            this.WindowTitles.Add("mark@telerikdomain.com - My Application");
            #endregion
        }
        
        #region Properties
        public UIOutlookBarCustom UIOutlookBarCustom
        {
            get
            {
                if ((this.mUIOutlookBarCustom == null))
                {
                    this.mUIOutlookBarCustom = new UIOutlookBarCustom(this);
                }
                return this.mUIOutlookBarCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIOutlookBarCustom mUIOutlookBarCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIOutlookBarCustom : WpfCustom
    {
        
        public UIOutlookBarCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.RadOutlookBar";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "OutlookBar";
            this.WindowTitles.Add("mark@telerikdomain.com - My Application");
            #endregion
        }
        
        #region Properties
        public WpfCustom UIRadOutlookBarItemCustomCalendar
        {
            get
            {
                if ((this.mUIRadOutlookBarItemCustomCalendar == null))
                {
                    this.mUIRadOutlookBarItemCustomCalendar = new WpfCustom(this);
                    #region Search Criteria
                    this.mUIRadOutlookBarItemCustomCalendar.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.RadOutlookBarItem";
                    this.mUIRadOutlookBarItemCustomCalendar.SearchProperties[WpfControl.PropertyNames.HelpText] = "RadOutlookBarItem";
                    this.mUIRadOutlookBarItemCustomCalendar.SearchProperties[WpfControl.PropertyNames.Instance] = "2";
                    this.mUIRadOutlookBarItemCustomCalendar.WindowTitles.Add("mark@telerikdomain.com - My Application");
                    #endregion
                }
                return this.mUIRadOutlookBarItemCustomCalendar;
            }
        }
        
        public WpfCustom UIRadOutlookBarItemCustomMail
        {
            get
            {
                if ((this.mUIRadOutlookBarItemCustomMail == null))
                {
                    this.mUIRadOutlookBarItemCustomMail = new WpfCustom(this);
                    #region Search Criteria
                    this.mUIRadOutlookBarItemCustomMail.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.RadOutlookBarItem";
                    this.mUIRadOutlookBarItemCustomMail.SearchProperties[WpfControl.PropertyNames.HelpText] = "RadOutlookBarItem";
                    this.mUIRadOutlookBarItemCustomMail.WindowTitles.Add("mark@telerikdomain.com - My Application");
                    #endregion
                }
                return this.mUIRadOutlookBarItemCustomMail;
            }
        }
        #endregion
        
        #region Fields
        private WpfCustom mUIRadOutlookBarItemCustomCalendar;
        
        private WpfCustom mUIRadOutlookBarItemCustomMail;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIMarktelerikdomaincomWindowCalendar : WpfWindow
    {
        
        public UIMarktelerikdomaincomWindowCalendar()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "mark@telerikdomain.com - calendar";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("mark@telerikdomain.com - calendar");
            #endregion
        }
        
        #region Properties
        public UIItemCustom1 UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom1(this);
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIItemCustom1 mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemCustom1 : WpfCustom
    {
        
        public UIItemCustom1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.MainView";
            this.WindowTitles.Add("mark@telerikdomain.com - calendar");
            #endregion
        }
        
        #region Properties
        public UIOutlookBarCustom1 UIOutlookBarCustom
        {
            get
            {
                if ((this.mUIOutlookBarCustom == null))
                {
                    this.mUIOutlookBarCustom = new UIOutlookBarCustom1(this);
                }
                return this.mUIOutlookBarCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIOutlookBarCustom1 mUIOutlookBarCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIOutlookBarCustom1 : WpfCustom
    {
        
        public UIOutlookBarCustom1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.RadOutlookBar";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "OutlookBar";
            this.WindowTitles.Add("mark@telerikdomain.com - calendar");
            #endregion
        }
        
        #region Properties
        public WpfCustom UIRadOutlookBarItemCustomCalendar
        {
            get
            {
                if ((this.mUIRadOutlookBarItemCustomCalendar == null))
                {
                    this.mUIRadOutlookBarItemCustomCalendar = new WpfCustom(this);
                    #region Search Criteria
                    this.mUIRadOutlookBarItemCustomCalendar.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.RadOutlookBarItem";
                    this.mUIRadOutlookBarItemCustomCalendar.SearchProperties[WpfControl.PropertyNames.HelpText] = "RadOutlookBarItem";
                    this.mUIRadOutlookBarItemCustomCalendar.SearchProperties[WpfControl.PropertyNames.Instance] = "2";
                    this.mUIRadOutlookBarItemCustomCalendar.WindowTitles.Add("mark@telerikdomain.com - calendar");
                    #endregion
                }
                return this.mUIRadOutlookBarItemCustomCalendar;
            }
        }
        
        public WpfCustom UIRadOutlookBarItemCustomMail
        {
            get
            {
                if ((this.mUIRadOutlookBarItemCustomMail == null))
                {
                    this.mUIRadOutlookBarItemCustomMail = new WpfCustom(this);
                    #region Search Criteria
                    this.mUIRadOutlookBarItemCustomMail.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.RadOutlookBarItem";
                    this.mUIRadOutlookBarItemCustomMail.SearchProperties[WpfControl.PropertyNames.HelpText] = "RadOutlookBarItem";
                    this.mUIRadOutlookBarItemCustomMail.WindowTitles.Add("mark@telerikdomain.com - calendar");
                    #endregion
                }
                return this.mUIRadOutlookBarItemCustomMail;
            }
        }
        #endregion
        
        #region Fields
        private WpfCustom mUIRadOutlookBarItemCustomCalendar;
        
        private WpfCustom mUIRadOutlookBarItemCustomMail;
        #endregion
    }
}
